### PR TITLE
Enable GitHub Actions for pull requests

### PR DESCRIPTION
**Pull request by claudiu-cristea**
.. also fixes a PHPStan complaint.

### CODE REVIEW

**Comment by k00ni** [comment]
That behavior is weird, because for my own pull requests it always started related Github Actions: https://github.com/sweetrdf/easyrdf/pulls?q=is%3Apr+is%3Aclosed

These are my settings, never had problems before. Maybe I overlooked something:

Bildschirmfoto von 2023-03-23 14-27-17

**Comment by claudiu-cristea** [comment]
@k00ni They are running now :)

**Comment by k00ni** [comment]
Haha, thank you @claudiu-cristea! 

I will check the PHPStan complain and try to upload a fix soon.

**Comment by claudiu-cristea** [comment]
Anyway, PHP7 should be removed. It's not supported anymore

**Comment by k00ni** [comment]
> Anyway, PHP7 should be removed. It's not supported anymore

That is correct, but there are still many people using it in production. As long as there is no blocker for fixes or required changes, I would rather keep PHP 7 compatibility in EasyRdf.

**Pull request merged**
