### PR TITLE
Add a method to remove resources from graph

### LINKED ISSUE #43: How to delete an entire resource from a graph?
We have `Graph::deleteResource()` which is not what I need. I need a way to wipe out an entire resource from the graph. It seems there's no such method

### PR DESCRIPTION
**Pull request by claudiu-cristea**
Fixes #43

### CODE REVIEW

**Comment by k00ni** [comment]
@claudiu-cristea thank you, its a helpful addition. Would you mind adding a unit test that covers the new code?

**Comment by claudiu-cristea** [comment]
I will add but very busy ATM

**Comment by k00ni** [comment]
I didn't check it thoroughly, but do you cover the following cases?

1. Resource A is subject
2. Resource A is predicate
3. Resource A is object

If I understand #43 correctly, all existing instances of a given resource is to be removed. Correct?

**Comment by k00ni** [comment]
> I'm not sure I understand your case

Lets suppose you have:

```
<http://foo/1> <http://bar/1> <http://baz/1> .
<http://example/2> <http://foo/1> <http://example/3> .
<http://example/a> <http://example/b> <http://foo/1> .
```

After calling `deleteEntireResource('http://foo/1');` all these triples are gone, because `http://foo/1` is part of them. Is that you want `deleteEntireResource` to work?

**Comment by k00ni** [comment]
@claudiu-cristea I refined your function based on my last comment. Does it act the way you described it?

**Comment by claudiu-cristea** [comment]
Initially I didn't think about the triples referring the deleted resources. I really don't know whether we need to delete also those triples. I'm thinking that they can be referred from other graphs (???). No strong opinion. However, if we follow those related resources, I think we need to make this optional (i.e., with an option). Let's not rush, I need t reflect more on this

**Comment by zozlak** [comment]
I guess what you want is to only delete all triples having a given subject.

In such a case I would suggest to make it the `easyrdf\Resource::deleteAll()` method or adjust the already existing `easyrdf\Resource::delete()` in a way it can be called with no parameters (which would be interpreted as "delete all").

The tricky part about it is the state of the `EasyRdf\Resource` object after the removal of all triples having it as a subject. If a given `EasyRdf\Resource` is not used as a predicate (property in easyrdf terminology) nor object (value) of any other triple, then it should be detached from the graph and become "dysfunctional" (which is not a real issue from the user perspective I guess). If not, it will still be a valid graph resource, just existing as a predicate and/or object but not as a subject.

The problem with the `easyrdf\Graph::deleteWholeResource()` is as outlined by @k00ni - in the easyrdf data model a resource represents both triples' subjects, predicates (properties) and objects so the `easyrdf\Graph::deleteWholeResource()` sounds quite ambigous.

**Comment by claudiu-cristea** [comment]
@zozlak 

> I guess what you want is to only delete all triples having a given subject.

Yes, this is exactly what I need.

> In such a case I would suggest to make it the easyrdf\Resource::deleteAll() method...

Sounds better. I will provide shortly some commits on this direction

**Comment by k00ni** [comment]
Closed for now to avoid stale PRs. Please get to me if you wanna continue here.

**Pull request closed without merging**
