### PR TITLE
Bumb min. PHP version to 8.0.0 + cleanup (mostly PHP-CS-Fixer)

### PR DESCRIPTION
**Pull request by k00ni**
Reason to use 8.0.0 as minimum PHP version is extended effort to maintain PHP 7.x compatibility as well as blocking new changes like #25 (which require PHP 8.0+).

### CODE REVIEW

**Comment by k00ni** [comment]
@zozlak @idimopoulos @ Removing PHP 7.x support was pretty straightforward. I cc'ed you just in case you wanna added something before I merge it into master.

**Comment by idimopoulos** [comment]
Thanks. Sorry for not doing it myself.. I really did not have time. But I will find some time to update the other PR as soon as possible.

**Comment by k00ni** [comment]
> Thanks. Sorry for not doing it myself.. I really did not have time. 

Don't worry, all good.

**Comment by idimopoulos** [comment]
Seems quite fine. I am pretty sure you can find little things that comply with 8.0 that would not comply with 7.4 but still, it is not necessary.

**Comment by k00ni** [comment]
> I am pretty sure you can find little things that comply with 8.0 that would not comply with 7.4 but still, it is not necessary.

What do you mean?

**Comment by idimopoulos** [comment]
> > I am pretty sure you can find little things that comply with 8.0 that would not comply with 7.4 but still, it is not necessary.
> 
> What do you mean?

No, just that you might be able to find usages of the new features that PHP 8 would bring, like Unions (string|object|null) or other but it is not really necessary nor it would provide any additional help right now, so I would go with the bare minimum upgrade too.

**Pull request merged**
